# Site settings
title: inbrief
email: getinbrief@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Debashis Barman is a Freelance Web Designer. He specializes in Minimalist Web Design, Responsive Layout and Web Typography.
baseurl: "/app-content/" # the subpath of your site, e.g. /blog/
url: "http://www.debashisbarman.in" # the base hostname & protocol for your site
twitter_username: getinbrief
github_username:  getinbrief
paginate: 3

# Build settings
markdown: kramdown
